// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ4LLiTbxhqAvDAoIJbt7JseS1qWArwNo',
    appId: '1:1057531841336:android:f0a1cd0d6dd8613731cfcd',
    messagingSenderId: '1057531841336',
    projectId: 'count-me-in-fe2e3',
    storageBucket: 'count-me-in-fe2e3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgAWmEWL45Y9QqZywHR6FFpbiwHQZVF_c',
    appId: '1:1057531841336:ios:38d42b47d756c56531cfcd',
    messagingSenderId: '1057531841336',
    projectId: 'count-me-in-fe2e3',
    storageBucket: 'count-me-in-fe2e3.firebasestorage.app',
    iosClientId:
        '1057531841336-d5j4npjmblnnuohm4qlub3rdpjpkb38m.apps.googleusercontent.com',
    iosBundleId: 'com.example.countMeIn',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgAWmEWL45Y9QqZywHR6FFpbiwHQZVF_c',
    appId: '1:1057531841336:ios:38d42b47d756c56531cfcd',
    messagingSenderId: '1057531841336',
    projectId: 'count-me-in-fe2e3',
    storageBucket: 'count-me-in-fe2e3.firebasestorage.app',
    iosClientId:
        '1057531841336-d5j4npjmblnnuohm4qlub3rdpjpkb38m.apps.googleusercontent.com',
    iosBundleId: 'com.example.countMeIn',
  );
}
